[package]
name = "libobs-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libobs-sys = {path = "../libobs-sys"}
log = {version = "0.4", features = ["std"]}